trigger:
- main

pool: 'DotNetQuiz Agent Pool'

variables:
   buildConfiguration: 'Release'
   dotnetVesrion: '6.0'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '$(dotnetVesrion).x'
    includePreviewVersions: true
    performMultiLevelLookup: true
  displayName: 'Install .NET Core SDK'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build of DotNetQuiz sln. Configuration --$(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.csproj'
  displayName: 'dotnet test of DotNetQuiz sln.'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(System.DefaultWorkingDirectory)/DotNetQuiz.Client/ClientApp'
    verbose: true
  displayName: 'Install NPM packages for DotNetQuiz.Client'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(System.DefaultWorkingDirectory)/DotNetQuiz.Client/ClientApp'
    customCommand: 'run build:azure'
  displayName: 'Build DotNetQuiz.Client for Azure deployment'

- task: FtpUpload@2
  inputs:
    credentialsOption: 'serviceEndpoint'
    serverEndpoint: 'DotNetQuiz AppService FTP'
    rootDirectory: '$(System.DefaultWorkingDirectory)/DotNetQuiz.Client/ClientApp/dist'
    filePatterns: '**'
    remoteDirectory: '/site/wwwroot'
    clean: false
    cleanContents: true
    preservePaths: false
    trustSSL: false
  displayName: 'Publishing DotNetQuiz Client static content to Azure AppService wwwroot folder'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'PublishProfile'
    PublishProfilePath: '$(System.DefaultWorkingDirectory)/DotNetQuiz.WebApi/Properties/PublishProfiles/*.pubxml'
    PublishProfilePassword: '$(DotNetQuiz_PublishProfile_Password)'
    packageForLinux: '$(System.DefaultWorkingDirectory)/DotNetQuiz.WebApi/bin/$(buildConfiguration)/net$(dotnetVesrion)/'
  displayName: 'Publishing DotNetQuiz Web API to Azure AppService'

