# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build:azure
  displayName: 'npm install and build DotNetQuizClient in Azure configuration'

- task: FtpUpload@2
  displayName: 'FTP Upload to App Service'
  inputs:
    serverEndpoint: 'DotNetQuiz AppService FTP'
    rootDirectory: 'DotNetQuiz.Client\ClientApp\dist'
    remoteDirectory: '\'
